/**
 * GitHub v3 REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Basic Error
 */
export interface GitHubBasicError {
  message?: string;
  documentation_url?: string;
  url?: string;
  status?: string;
}
