/**
 * GitHub v3 REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GitHubBranchRestrictionPolicyAppsInnerPermissions } from './branchRestrictionPolicyAppsInnerPermissions';
import { GitHubBranchRestrictionPolicyAppsInnerOwner } from './branchRestrictionPolicyAppsInnerOwner';

export interface GitHubBranchRestrictionPolicyAppsInner {
  id?: number;
  slug?: string;
  node_id?: string;
  owner?: GitHubBranchRestrictionPolicyAppsInnerOwner;
  name?: string;
  description?: string;
  external_url?: string;
  html_url?: string;
  created_at?: string;
  updated_at?: string;
  permissions?: GitHubBranchRestrictionPolicyAppsInnerPermissions;
  events?: Array<string>;
}
