/**
 * GitHub v3 REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Whether to set the branch as read-only. If this is true, users will not be able to push to the branch.
 */
export interface GitHubBranchProtectionLockBranch {
  enabled?: boolean;
}
