/**
 * GitHub v3 REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GitHubBranchRestrictionPolicyUsersInner } from './branchRestrictionPolicyUsersInner';
import { GitHubBranchRestrictionPolicyTeamsInner } from './branchRestrictionPolicyTeamsInner';
import { GitHubBranchRestrictionPolicyAppsInner } from './branchRestrictionPolicyAppsInner';

/**
 * Branch Restriction Policy
 */
export interface GitHubBranchRestrictionPolicy {
  url: string;
  users_url: string;
  teams_url: string;
  apps_url: string;
  users: Array<GitHubBranchRestrictionPolicyUsersInner>;
  teams: Array<GitHubBranchRestrictionPolicyTeamsInner>;
  apps: Array<GitHubBranchRestrictionPolicyAppsInner>;
}
