/**
 * GitHub v3 REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface GitHubBranchRestrictionPolicyTeamsInner {
  id?: number;
  node_id?: string;
  url?: string;
  html_url?: string;
  name?: string;
  slug?: string;
  description?: string | null;
  privacy?: string;
  permission?: string;
  members_url?: string;
  repositories_url?: string;
  parent?: string | null;
}
