/**
 * GitHub v3 REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GitHubBranchProtectionRequiredLinearHistory } from './branchProtectionRequiredLinearHistory';
import { GitHubBranchProtectionRequiredSignatures } from './branchProtectionRequiredSignatures';
import { GitHubBranchProtectionAllowForkSyncing } from './branchProtectionAllowForkSyncing';
import { GitHubProtectedBranchAdminEnforced } from './protectedBranchAdminEnforced';
import { GitHubProtectedBranchRequiredStatusCheck } from './protectedBranchRequiredStatusCheck';
import { GitHubBranchRestrictionPolicy } from './branchRestrictionPolicy';
import { GitHubBranchProtectionLockBranch } from './branchProtectionLockBranch';
import { GitHubProtectedBranchPullRequestReview } from './protectedBranchPullRequestReview';

/**
 * Branch Protection
 */
export interface GitHubBranchProtection {
  url?: string;
  enabled?: boolean;
  required_status_checks?: GitHubProtectedBranchRequiredStatusCheck;
  enforce_admins?: GitHubProtectedBranchAdminEnforced;
  required_pull_request_reviews?: GitHubProtectedBranchPullRequestReview;
  restrictions?: GitHubBranchRestrictionPolicy;
  required_linear_history?: GitHubBranchProtectionRequiredLinearHistory;
  allow_force_pushes?: GitHubBranchProtectionRequiredLinearHistory;
  allow_deletions?: GitHubBranchProtectionRequiredLinearHistory;
  block_creations?: GitHubBranchProtectionRequiredLinearHistory;
  required_conversation_resolution?: GitHubBranchProtectionRequiredLinearHistory;
  name?: string;
  protection_url?: string;
  required_signatures?: GitHubBranchProtectionRequiredSignatures;
  lock_branch?: GitHubBranchProtectionLockBranch;
  allow_fork_syncing?: GitHubBranchProtectionAllowForkSyncing;
}
