/**
 * GitHub v3 REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Code Of Conduct
 */
export interface GitHubCodeOfConduct {
  key: string;
  name: string;
  url: string;
  body?: string;
  html_url: string | null;
}
