/**
 * GitHub v3 REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The set of permissions for the GitHub app
 */
export interface GitHubIntegrationPermissions {
  [key: string]: string | any;

  issues?: string;
  checks?: string;
  metadata?: string;
  contents?: string;
  deployments?: string;
}
