/**
 * GitHub v3 REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GitHubProtectedBranchPullRequestReviewBypassPullRequestAllowances } from './protectedBranchPullRequestReviewBypassPullRequestAllowances';
import { GitHubProtectedBranchPullRequestReviewDismissalRestrictions } from './protectedBranchPullRequestReviewDismissalRestrictions';

/**
 * Protected Branch Pull Request Review
 */
export interface GitHubProtectedBranchPullRequestReview {
  url?: string;
  dismissal_restrictions?: GitHubProtectedBranchPullRequestReviewDismissalRestrictions;
  bypass_pull_request_allowances?: GitHubProtectedBranchPullRequestReviewBypassPullRequestAllowances;
  dismiss_stale_reviews: boolean;
  require_code_owner_reviews: boolean;
  required_approving_review_count?: number;
  /**
   * Whether the most recent push must be approved by someone other than the person who pushed it.
   */
  require_last_push_approval?: boolean;
}
