/**
 * GitHub v3 REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GitHubIntegration } from './integration';
import { GitHubSimpleUser } from './simpleUser';
import { GitHubTeam } from './team';

/**
 * Allow specific users, teams, or apps to bypass pull request requirements.
 */
export interface GitHubProtectedBranchPullRequestReviewBypassPullRequestAllowances {
  /**
   * The list of users allowed to bypass pull request requirements.
   */
  users?: Array<GitHubSimpleUser>;
  /**
   * The list of teams allowed to bypass pull request requirements.
   */
  teams?: Array<GitHubTeam>;
  /**
   * The list of apps allowed to bypass pull request requirements.
   */
  apps?: Array<GitHubIntegration>;
}
