/**
 * GitHub v3 REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GitHubProtectedBranchRequiredStatusCheckChecksInner } from './protectedBranchRequiredStatusCheckChecksInner';

/**
 * Protected Branch Required Status Check
 */
export interface GitHubProtectedBranchRequiredStatusCheck {
  url?: string;
  enforcement_level?: string;
  contexts: Array<string>;
  checks: Array<GitHubProtectedBranchRequiredStatusCheckChecksInner>;
  contexts_url?: string;
  strict?: boolean;
}
