/**
 * GitHub v3 REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Protected Branch Admin Enforced
 */
export interface GitHubProtectedBranchAdminEnforced {
  url: string;
  enabled: boolean;
}
