/**
 * GitHub v3 REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GitHubIntegration } from './integration';
import { GitHubSimpleUser } from './simpleUser';
import { GitHubTeam } from './team';

export interface GitHubProtectedBranchPullRequestReviewDismissalRestrictions {
  /**
   * The list of users with review dismissal access.
   */
  users?: Array<GitHubSimpleUser>;
  /**
   * The list of teams with review dismissal access.
   */
  teams?: Array<GitHubTeam>;
  /**
   * The list of apps with review dismissal access.
   */
  apps?: Array<GitHubIntegration>;
  url?: string;
  users_url?: string;
  teams_url?: string;
}
