/**
 * GitHub v3 REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GitHubSecurityAndAnalysisAdvancedSecurity } from './securityAndAnalysisAdvancedSecurity';

export interface GitHubSecurityAndAnalysis {
  advanced_security?: GitHubSecurityAndAnalysisAdvancedSecurity;
  secret_scanning?: GitHubSecurityAndAnalysisAdvancedSecurity;
  secret_scanning_push_protection?: GitHubSecurityAndAnalysisAdvancedSecurity;
}
