/**
 * GitHub v3 REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface GitHubSecurityAndAnalysisAdvancedSecurity {
  status?: GitHubSecurityAndAnalysisAdvancedSecurity.StatusEnum;
}
export namespace GitHubSecurityAndAnalysisAdvancedSecurity {
  export type StatusEnum = 'enabled' | 'disabled';
  export const StatusEnum = {
    Enabled: 'enabled' as StatusEnum,
    Disabled: 'disabled' as StatusEnum,
  };
}
