/**
 * GitHub v3 REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GitHubBranchProtection } from './branchProtection';
import { GitHubShortBranchCommit } from './shortBranchCommit';

/**
 * Short Branch
 */
export interface GitHubShortBranch {
  name: string;
  commit: GitHubShortBranchCommit;
  protected: boolean;
  protection?: GitHubBranchProtection;
  protection_url?: string;
}
