/**
 * GitHub v3 REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GitHubNullableTeamSimple } from './nullableTeamSimple';
import { GitHubTeamPermissions } from './teamPermissions';

/**
 * Groups of organization members that gives permissions on specified repositories.
 */
export interface GitHubTeam {
  id: number;
  node_id: string;
  name: string;
  slug: string;
  description: string | null;
  privacy?: string;
  permission: string;
  permissions?: GitHubTeamPermissions;
  url: string;
  html_url: string;
  members_url: string;
  repositories_url: string;
  parent: GitHubNullableTeamSimple | null;
}
