/**
 * GitHub v3 REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GitHubWebhookSecurityAndAnalysisChangesFrom } from './webhookSecurityAndAnalysisChangesFrom';

export interface GitHubWebhookSecurityAndAnalysisChanges {
  from?: GitHubWebhookSecurityAndAnalysisChangesFrom;
}
