FROM node:22.12-alpine
WORKDIR /usr/src/app
RUN npm install -g @angular/cli@19
COPY package.json /usr/src/app/package.json
RUN npm install
EXPOSE 4200
CMD ["ng", "serve", "--host", "0.0.0.0", "--poll=2000", "--port", "4200", "--disable-host-check"]
